import '../../domain/analysis/analysis_module_code.dart';
import '../../domain/insight/insight_slot_code.dart';
import '../../domain/insight/insight_template.dart';
import '../../domain/insight/insight_type_code.dart';

class DefaultInsightTemplates {
  static const all = <InsightTemplate>[
    InsightTemplate(
      code: 'daily_brief_complete_day_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.dailyBrief,
      type: InsightTypeCode.dailyCompleteDay,
      eyebrowTemplate: 'DAILY BRIEF - TODAY',
      bodyTemplate:
          '{dayLabel} TIR was {tir}%, {tirDeltaPhrase} your 2-week average ({avgTir14}%). {eveningSentence} CV was {cv}%, {cvDeltaPhrase} your typical {avgCv14}%. {nightSentence}',
      footerTemplate: 'Based on {observedDays14} days of data',
      requiredFacts: [
        'dayLabel',
        'tir',
        'tirDeltaPhrase',
        'avgTir14',
        'eveningSentence',
        'cv',
        'cvDeltaPhrase',
        'avgCv14',
        'nightSentence',
        'observedDays14',
      ],
      priority: 10,
    ),
    InsightTemplate(
      code: 'daily_brief_not_enough_data_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.dailyBrief,
      type: InsightTypeCode.dailyNotEnoughData,
      eyebrowTemplate: 'DAILY BRIEF - TODAY',
      bodyTemplate:
          'Not enough CGM data yet. Connect a data source and let the app collect readings before generating insight text.',
      footerTemplate: 'Waiting for more data',
      priority: 90,
    ),
    InsightTemplate(
      code: 'weekly_review_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.weeklyReview,
      type: InsightTypeCode.weeklyReview,
      eyebrowTemplate: 'WEEK IN REVIEW - {weekRange}',
      bodyTemplate:
          'Last week TIR was {tir7}%, {tirDeltaPhrase} the prior week ({prevTir7}%). {bestDaySentence} {longestHighSentence} CV was {cv7}% for the reviewed week.',
      footerTemplate: 'n={readingCount7} readings - rolling 7-day review',
      requiredFacts: [
        'weekRange',
        'tir7',
        'tirDeltaPhrase',
        'prevTir7',
        'bestDaySentence',
        'longestHighSentence',
        'cv7',
        'readingCount7',
      ],
      priority: 20,
    ),
    InsightTemplate(
      code: 'pattern_dawn_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.patternCard,
      type: InsightTypeCode.dawnPattern,
      iconKey: 'dawn',
      titleTemplate: '{dawnTitle}',
      bodyTemplate: '{dawnBody}',
      footerTemplate:
          'n={observedMornings} mornings - threshold +1.2 {glucoseUnit} - auto-detected',
      requiredFacts: ['dawnTitle', 'dawnBody', 'observedMornings'],
      priority: 30,
    ),
    InsightTemplate(
      code: 'pattern_volatile_period_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.patternCard,
      type: InsightTypeCode.volatilePeriod,
      iconKey: 'volatility',
      titleTemplate: '{periodLabel} window is your most volatile',
      bodyTemplate:
          '{periodLabel} has CV {periodCv}%, TIR {periodTir}%, and average glucose {periodMean} {glucoseUnit} across the selected window.',
      footerTemplate: 'n={periodReadingCount} readings - period CV ranking',
      requiredFacts: [
        'periodLabel',
        'periodCv',
        'periodTir',
        'periodMean',
        'periodReadingCount',
      ],
      priority: 40,
    ),
    InsightTemplate(
      code: 'pattern_stable_period_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.patternCard,
      type: InsightTypeCode.stablePeriod,
      iconKey: 'stability',
      titleTemplate: '{periodLabel} window is your most stable',
      bodyTemplate:
          '{periodLabel} combines CV {periodCv}% with TIR {periodTir}%, making it the best-controlled period in the current dataset.',
      footerTemplate: 'n={periodReadingCount} readings - TIR/CV composite',
      requiredFacts: [
        'periodLabel',
        'periodCv',
        'periodTir',
        'periodReadingCount',
      ],
      priority: 50,
    ),
    InsightTemplate(
      code: 'pattern_weekday_gap_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.patternCard,
      type: InsightTypeCode.weekdayGap,
      iconKey: 'weekday',
      titleTemplate: '{weekdayGapTitle}',
      bodyTemplate:
          'Average weekend TIR is {weekendTir}%, {weekdayGapDelta} percentage points {weekdayGapDirection} weekdays ({weekdayTir}%).',
      footerTemplate: 'n={weekdayGapDays} days - weekday/weekend split',
      requiredFacts: [
        'weekdayGapTitle',
        'weekendTir',
        'weekdayGapDelta',
        'weekdayGapDirection',
        'weekdayTir',
        'weekdayGapDays',
      ],
      priority: 60,
    ),
    InsightTemplate(
      code: 'pattern_not_enough_data_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.patternCard,
      type: InsightTypeCode.notEnoughPatternData,
      iconKey: 'generic',
      titleTemplate: 'Not enough pattern data yet',
      bodyTemplate:
          'The engine needs more CGM readings before it can identify repeated dawn, period, or weekday patterns.',
      footerTemplate: 'n={readingCount14} readings - waiting for more data',
      requiredFacts: ['readingCount14'],
      priority: 100,
    ),
    InsightTemplate(
      code: 'calendar_best_day_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.calendarSummary,
      type: InsightTypeCode.calendarBestDay,
      bodyTemplate: '{weekdayLabel} {dateLabel} (TIR {tir}%)',
      requiredFacts: ['weekdayLabel', 'dateLabel', 'tir'],
      priority: 10,
    ),
    InsightTemplate(
      code: 'calendar_weekday_weekend_same_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.calendarPattern,
      type: InsightTypeCode.calendarWeekdayWeekend,
      bodyTemplate:
          'Weekdays and weekends look about the same (weekday avg {weekdayTir}%, weekend avg {weekendTir}%).',
      requiredFacts: ['samePattern', 'weekdayTir', 'weekendTir'],
      priority: 10,
    ),
    InsightTemplate(
      code: 'calendar_weekday_weekend_weekend_lower_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.calendarPattern,
      type: InsightTypeCode.calendarWeekdayWeekend,
      bodyTemplate:
          'Weekends tend to be {delta}% lower TIR (Sat/Sun avg {weekendTir}% vs weekday {weekdayTir}%).',
      requiredFacts: ['delta', 'weekdayTir', 'weekendTir', 'weekendLower'],
      priority: 20,
    ),
    InsightTemplate(
      code: 'calendar_weekday_weekend_weekend_higher_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.calendarPattern,
      type: InsightTypeCode.calendarWeekdayWeekend,
      bodyTemplate:
          'Weekends tend to be {delta}% higher TIR (Sat/Sun avg {weekendTir}% vs weekday {weekdayTir}%).',
      requiredFacts: ['delta', 'weekdayTir', 'weekendTir', 'weekendHigher'],
      priority: 30,
    ),
    InsightTemplate(
      code: 'calendar_weekday_weekend_not_enough_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.calendarPattern,
      type: InsightTypeCode.calendarWeekdayWeekend,
      bodyTemplate: 'Not enough data yet to compare weekdays vs weekends.',
      requiredFacts: ['notEnoughData'],
      priority: 90,
    ),
    InsightTemplate(
      code: 'calendar_best_streak_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.calendarPattern,
      type: InsightTypeCode.calendarBestStreak,
      bodyTemplate:
          'Your best stretch was {startDate}-{endDate}: {streakDays} consecutive days above {threshold}% TIR.',
      requiredFacts: ['startDate', 'endDate', 'streakDays', 'threshold'],
      priority: 10,
    ),
    InsightTemplate(
      code: 'calendar_best_streak_short_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.calendarPattern,
      type: InsightTypeCode.calendarBestStreak,
      bodyTemplate:
          'Your longest run of days above {threshold}% TIR is too short to highlight yet.',
      requiredFacts: ['shortStreak', 'threshold'],
      priority: 80,
    ),
    InsightTemplate(
      code: 'calendar_best_streak_not_enough_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.calendarPattern,
      type: InsightTypeCode.calendarBestStreak,
      bodyTemplate: 'Not enough data to identify your best stretch yet.',
      requiredFacts: ['notEnoughData'],
      priority: 90,
    ),
    InsightTemplate(
      code: 'calendar_empty_state_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.calendarEmptyState,
      type: InsightTypeCode.calendarNoData,
      bodyTemplate:
          'No CGM readings were found in the calendar window. Connect xDrip+ Local or Nightscout API to view the heatmap.',
      priority: 10,
    ),
    InsightTemplate(
      code: 'period_overview_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.periodSummary,
      type: InsightTypeCode.periodOverview,
      bodyTemplate:
          'Your {worstPeriod} window is the most challenging period by time-in-range ({worstTir}%). {bestPeriod} is currently strongest, with TIR {bestTir}% and CV {bestCv}%. {variablePeriod} has the highest variability (CV {variableCv}%), while {peakPeriod} reaches the highest observed peak ({peakValue} {glucoseUnit}).',
      footerTemplate:
          'Based on {days} days | n={readingCount} readings | all times local',
      requiredFacts: [
        'worstPeriod',
        'worstTir',
        'bestPeriod',
        'bestTir',
        'bestCv',
        'variablePeriod',
        'variableCv',
        'peakPeriod',
        'peakValue',
        'days',
        'readingCount',
      ],
      priority: 10,
    ),
    InsightTemplate(
      code: 'period_overview_not_enough_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.periodSummary,
      type: InsightTypeCode.periodOverview,
      bodyTemplate: 'Not enough CGM data yet for period analysis.',
      footerTemplate: 'Based on {days} days | no readings available',
      requiredFacts: ['notEnoughData', 'days'],
      priority: 90,
    ),
    InsightTemplate(
      code: 'period_weekday_weekend_same_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.periodPattern,
      type: InsightTypeCode.periodWeekdayWeekend,
      bodyTemplate:
          'Your weekday and weekend glucose patterns look about the same.',
      requiredFacts: ['samePattern'],
      priority: 10,
    ),
    InsightTemplate(
      code: 'period_weekday_weekend_weekday_higher_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.periodPattern,
      type: InsightTypeCode.periodWeekdayWeekend,
      bodyTemplate:
          'Weekday time-in-range is {delta}% higher than weekend time-in-range in this window.',
      requiredFacts: ['delta', 'weekdayHigher'],
      priority: 20,
    ),
    InsightTemplate(
      code: 'period_weekday_weekend_weekend_higher_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.periodPattern,
      type: InsightTypeCode.periodWeekdayWeekend,
      bodyTemplate:
          'Weekend time-in-range is {delta}% higher than weekday time-in-range in this window.',
      requiredFacts: ['delta', 'weekendHigher'],
      priority: 30,
    ),
    InsightTemplate(
      code: 'period_weekday_weekend_not_enough_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.periodPattern,
      type: InsightTypeCode.periodWeekdayWeekend,
      bodyTemplate:
          'More weekday and weekend readings are needed before comparing these patterns.',
      requiredFacts: ['notEnoughData'],
      priority: 90,
    ),
    InsightTemplate(
      code: 'period_empty_state_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.periodEmptyState,
      type: InsightTypeCode.periodNoData,
      bodyTemplate:
          'No CGM readings were found in the selected analysis window. Connect xDrip+ Local or Nightscout API to view period analysis.',
      priority: 10,
    ),
    InsightTemplate(
      code: 'agp_dawn_rise_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.agpObservation,
      type: InsightTypeCode.agpDawnRise,
      bodyTemplate:
          'Pre-dawn rise ({windowLabel}): median climbs +{avgRise} {glucoseUnit}. Consistent on {consistentDays}/{days} days.',
      requiredFacts: ['windowLabel', 'avgRise', 'consistentDays', 'days'],
      priority: 10,
    ),
    InsightTemplate(
      code: 'agp_midday_recovery_better_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.agpObservation,
      type: InsightTypeCode.agpMiddayRecovery,
      bodyTemplate:
          'Midday recovery ({windowLabel}): median stays around {midMedian} {glucoseUnit}. Better controlled than the morning window.',
      requiredFacts: ['windowLabel', 'midMedian', 'betterThanMorning'],
      priority: 10,
    ),
    InsightTemplate(
      code: 'agp_midday_recovery_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.agpObservation,
      type: InsightTypeCode.agpMiddayRecovery,
      bodyTemplate:
          'Midday recovery ({windowLabel}): median stays around {midMedian} {glucoseUnit}.',
      requiredFacts: ['windowLabel', 'midMedian'],
      priority: 20,
    ),
    InsightTemplate(
      code: 'agp_night_stability_stable_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.agpObservation,
      type: InsightTypeCode.agpNightStability,
      bodyTemplate:
          'Night stability ({windowLabel}): narrow p25-p75 band, your most predictable window.',
      requiredFacts: ['windowLabel', 'stableNight'],
      priority: 10,
    ),
    InsightTemplate(
      code: 'agp_night_stability_variable_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.agpObservation,
      type: InsightTypeCode.agpNightStability,
      bodyTemplate:
          'Night window ({windowLabel}): variability is wider than the daytime average.',
      requiredFacts: ['windowLabel', 'variableNight'],
      priority: 20,
    ),
    InsightTemplate(
      code: 'agp_observation_not_enough_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.agpObservation,
      type: InsightTypeCode.agpNoData,
      bodyTemplate: 'Not enough CGM data yet for time-window observations.',
      requiredFacts: ['notEnoughData'],
      priority: 90,
    ),
    InsightTemplate(
      code: 'agp_empty_state_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.agpEmptyState,
      type: InsightTypeCode.agpNoData,
      bodyTemplate:
          'No CGM readings were found in the selected AGP window. Connect xDrip+ Local or Nightscout API to view the ambulatory glucose profile.',
      priority: 10,
    ),
    InsightTemplate(
      code: 'glucose_events_count_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.glucoseEventsCountSummary,
      type: InsightTypeCode.glucoseEventsCount,
      bodyTemplate: '{count} auto-detected {eventWord} - {dayLabel}',
      requiredFacts: ['count', 'eventWord', 'dayLabel'],
      priority: 10,
    ),
    InsightTemplate(
      code: 'glucose_events_shortcut_no_high_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.glucoseEventsShortcutEmpty,
      type: InsightTypeCode.glucoseEventsShortcutNoHigh,
      bodyTemplate: 'No high episode in last 14 days',
      priority: 10,
    ),
    InsightTemplate(
      code: 'glucose_events_shortcut_no_low_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.glucoseEventsShortcutEmpty,
      type: InsightTypeCode.glucoseEventsShortcutNoLow,
      bodyTemplate: 'No low episode in last 14 days',
      priority: 10,
    ),
    InsightTemplate(
      code: 'glucose_events_empty_state_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.glucoseEventsEmptyState,
      type: InsightTypeCode.glucoseEventsNoData,
      bodyTemplate: 'No auto-detected events for this day yet.',
      priority: 10,
    ),
    InsightTemplate(
      code: 'glucose_event_first_reading_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.glucoseEventRow,
      type: InsightTypeCode.glucoseEventFirstReading,
      bodyTemplate: 'Wake-up reading',
      priority: 10,
    ),
    InsightTemplate(
      code: 'glucose_event_high_episode_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.glucoseEventRow,
      type: InsightTypeCode.glucoseEventHighEpisode,
      bodyTemplate:
          '{durationMinutes} min above {highThreshold}, area {area}, peak {peak}',
      requiredFacts: ['durationMinutes', 'area', 'peak'],
      priority: 10,
    ),
    InsightTemplate(
      code: 'glucose_event_low_episode_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.glucoseEventRow,
      type: InsightTypeCode.glucoseEventLowEpisode,
      bodyTemplate: '{durationMinutes} min below {lowThreshold}, nadir {nadir}',
      requiredFacts: ['durationMinutes', 'nadir'],
      priority: 10,
    ),
    InsightTemplate(
      code: 'glucose_event_rise_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.glucoseEventRow,
      type: InsightTypeCode.glucoseEventRise,
      bodyTemplate: 'Rise +{rate} {glucoseRateUnit}, local peak',
      requiredFacts: ['rate'],
      priority: 10,
    ),
    InsightTemplate(
      code: 'glucose_event_recovery_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.glucoseEventRow,
      type: InsightTypeCode.glucoseEventRecovery,
      bodyTemplate: 'Returned to range',
      priority: 10,
    ),
    InsightTemplate(
      code: 'glucose_event_stable_window_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.glucoseEventRow,
      type: InsightTypeCode.glucoseEventStableWindow,
      bodyTemplate: '{hours}h in range',
      requiredFacts: ['hours'],
      priority: 10,
    ),
    InsightTemplate(
      code: 'glucose_event_dawn_phenomenon_v1',
      module: AnalysisModuleCode.insights,
      slot: InsightSlotCode.glucoseEventRow,
      type: InsightTypeCode.glucoseEventDawnPhenomenon,
      bodyTemplate: 'Pre-dawn rise +{rise} {glucoseUnit} (04-07)',
      requiredFacts: ['rise'],
      priority: 10,
    ),
  ];
}
